packages:
  - packages/*
  - website
catalog:
  '@antfu/eslint-config': ^3.12.1
  '@commitlint/config-conventional': ^19.6.0
  '@commitlint/prompt-cli': ^19.6.1
  '@pinia/nuxt': ^0.9.0
  '@vueuse/nuxt': ^12.2.0
  conventional-changelog-atom: ^5.0.0
  eslint: ^9.17.0
  lint-staged: ^15.2.0
  nuxt: ^3.15.0
  pinia: ^2.3.0
  simple-git-hooks: ^2.11.0
  vue-router: latest
  vue-tsc: latest
  vue: latest
