packages:
  - packages/*
  - website
catalog:
  '@antfu/eslint-config': ^4.3.0
  '@commitlint/config-conventional': ^19.7.1
  '@commitlint/prompt-cli': ^19.7.1
  '@pinia/nuxt': ^0.10.1
  conventional-changelog-atom: ^5.0.0
  eslint: ^9.21.0
  eslint-plugin-format: ^1.0.1
  lint-staged: ^15.4.3
  nuxt: ^3.15.4
  simple-git-hooks: ^2.11.1
  vue: latest
  vue-router: latest
  vue-tsc: latest
