shamefullyHoist: true
engineStrict: true
nodeVersion: 24.1.0
packageManagerStrictVersion: true

packages:
  - packages/*
  - website

overrides:
  vite: npm:rolldown-vite@latest

catalogs:
  dev:
    '@commitlint/config-conventional': ^19.8.1
    '@commitlint/prompt-cli': ^19.8.1
    '@pinia/nuxt': ^0.11.0
    conventional-changelog-atom: ^5.0.0
    lint-staged: ^16.1.0
    simple-git-hooks: ^2.13.0
  lint:
    '@antfu/eslint-config': ^4.13.2
    eslint: ^9.28.0
    eslint-plugin-format: ^1.0.1
    vue-tsc: ^2.2.10
  prod:
    '@iconify-json/lucide': ^1.2.45
    '@nuxt/ui-pro': ^3.1.3
    nuxt: ^3.17.4
    pnpm-workspace-yaml: ^0.3.1
    vue: ^3.5.16
    vue-router: ^4.5.1

onlyBuiltDependencies:
  - esbuild
