packages:
  - .
  - packages/*
catalog:
  '@antfu/eslint-config': ^3.12.1
  '@commitlint/config-conventional': ^19.6.0
  '@commitlint/prompt-cli': ^19.6.1
  conventional-changelog-atom: ^5.0.0
  eslint: ^9.17.0
  lint-staged: ^15.2.11
  simple-git-hooks: ^2.11.1
