name: CI

on: [push, pull_request]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

env:
  SKIP_INSTALL_SIMPLE_GIT_HOOKS: 1

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # https://vercel.com/guides/corepack-errors-github-actions
      - run: npm install -g corepack@latest && corepack enable

      - name: Set node
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: lts/*

      - name: Install commitlint
        run: pnpm install -w conventional-changelog-conventionalcommits commitlint@latest

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: npx commitlint --config .config/commitlint.ts --last --verbose

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: >
          npx commitlint \
            --config .config/commitlint.ts \
            --from ${{ github.event.pull_request.base.sha }} \
            --to ${{ github.event.pull_request.head.sha }} \
            --verbose
